import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner/banner'
import NavBar from '../components/nav/navbar'
import { getPopularVideos,getVideos ,getWatchItAgainVideos, } from '../lib/video'

import { redirectUser } from "../utils/redirectUser"


import SectionCards from '../components/card/sectioncard'


export async function getServerSideProps(context) {

  const { userId, token } = await redirectUser(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  


  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  const ACTION_ADVANTURE =  await getVideos("Action advanture Games PS4 Trailer");
  const FPS =  await getVideos("fps Games PS4 Trailer");
  const RPG =  await getVideos("rpg Games PS4 Trailer");
  const JRPG =  await getVideos("Jrpg Games PS4 Trailer");



const popularVideos = await getPopularVideos();





  return {
    props: {ACTION_ADVANTURE,FPS,RPG,JRPG,popularVideos, watchItAgainVideos,}, // will be passed to the page component as props
  };
}

export default function Home({ACTION_ADVANTURE,FPS,RPG,JRPG,popularVideos,
  watchItAgainVideos,}) {

 
  

  return (
    <div className={styles.container}>
      <Head>
        <title>GAME FLIX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
      <NavBar />

      <Banner 
      videoId="EE-4GvjKcfs"
      title="God of War Ragnarök"
      subTitle="God of War"
      imgUrl="/static/Gowragnarock.jpg"
        />
       <div className={styles.sectionWrapper}>
    
      <SectionCards title="ACTION-ADVANTURE" videos={ACTION_ADVANTURE} size="medium" /> 
      <SectionCards title="FPS" videos={FPS} size="medium" /> 

      <SectionCards
            title="Watch it again"
            videos={watchItAgainVideos}
            size="small"
          />

      <SectionCards title="RPG" videos={RPG} size="medium" /> 
      <SectionCards title="JRPG" videos={JRPG} size="medium" /> 
   
      <SectionCards title="POPULAR" videos={popularVideos} size="large" /> 
      
      </div>
      </div>
   


    </div>
  )
}
